Serving HTTP on 0.0.0.0 port 8000 ...
Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/SimpleHTTPServer.py", line 235, in <module>
    test()
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/SimpleHTTPServer.py", line 231, in test
    BaseHTTPServer.test(HandlerClass, ServerClass)
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/BaseHTTPServer.py", line 610, in test
    httpd.serve_forever()
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/SocketServer.py", line 231, in serve_forever
    poll_interval)
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/SocketServer.py", line 150, in _eintr_retry
    return func(*args)
KeyboardInterrupt
127.0.0.1 - - [21/Aug/2017 00:10:54] code 404, message File not found
127.0.0.1 - - [21/Aug/2017 00:10:54] "GET /static/autocomplete.html HTTP/1.1" 404 -
127.0.0.1 - - [21/Aug/2017 00:10:55] code 404, message File not found
127.0.0.1 - - [21/Aug/2017 00:10:55] "GET /favicon.ico HTTP/1.1" 404 -
127.0.0.1 - - [21/Aug/2017 00:11:03] "GET /autocomplete.html HTTP/1.1" 200 -
127.0.0.1 - - [21/Aug/2017 00:13:14] "GET /autocomplete.html HTTP/1.1" 200 -
127.0.0.1 - - [21/Aug/2017 00:13:54] "GET /autocomplete.html HTTP/1.1" 200 -
127.0.0.1 - - [21/Aug/2017 00:13:58] code 404, message File not found
127.0.0.1 - - [21/Aug/2017 00:13:58] "GET /equity/scrips HTTP/1.1" 404 -
